name: Devsecops End to End Pipeline 

on:
  push:
    branches: [ main ]  

jobs:
    
    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml

    docker-lint:
        uses: ./.github/workflows/docker-lint.yml

    image-scan:
        uses: ./.github/workflows/image-scan.yml

    deploy-to-server:
        uses: ./.github/workflows/deploy-to-server.yml  