name: Devsecops End to End Pipeline 

on:
  push:
    branches:
      - main
jobs:
    #CI (Continuous Integration With security scanning)
    code-quality-scan:
        uses: ./.github/workflows/code_quality.yml

    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml  
        secrets: inherit

    dependency-scan:
        uses: ./.github/workflows/Dependency-scan.yml
        
    docker-scan:
        uses: ./.github/workflows/docker-lint.yml

    # build once the security scanning is successful
    build:
        needs: [code-quality-scan, secrets-scan, dependency-scan, docker-scan]  
        uses: ./.github/workflows/docker-build-push.yml  
        secrets: inherit

    trivy:
        needs: [build]
        uses: ./.github/workflows/image-scan.yml