# uses Trivy image scanner for CVEs - Docker image

name: image scanner

on: 
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  image-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Trivy Scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ inputs.image }}
          severity: 'CRITICAL,HIGH'
          exit-code: '1'